"""Product-owned deterministic ECAD design kernel.

The kernel accepts only typed, revision-scoped commands.  It is deliberately
independent from models and MCP transports: agents may propose commands, but
only this package can stage and commit canonical design state.
"""

from .adapter import revision_to_verification_board, to_verification_board
from .commit_authority import (
    COMMIT_AUTHORIZATION_SCOPE,
    COMMIT_AUTHORIZATION_VERSION,
    CommitAuthorityClockRollback,
    CommitAuthorization,
    CommitAuthorizationClaims,
    CommitAuthorizationError,
    ConsumedCommitAuthorization,
    ExpiredCommitAuthorization,
    HmacCommitAuthority,
    HmacCommitVerifier,
    InvalidCommitAuthorization,
    ReleaseApprovalEvidence,
    ReplayedCommitAuthorization,
    commit_command_hashes_digest,
)
from .engine import (
    ApprovalMismatch,
    CommandConflict,
    DesignKernel,
    KernelError,
    LockedObject,
    StaleRevision,
    TransactionNotCommittable,
)
from .model import (
    CommandKind,
    Component,
    CopperZone,
    DesignCommand,
    DesignGraph,
    DesignRevision,
    DesignTransaction,
    FootprintHole,
    FootprintPad,
    FootprintPlacement,
    InvariantViolation,
    Net,
    PinDefinition,
    PinRef,
    PointNm,
    SchematicJunction,
    SchematicWire,
    SemanticDiff,
    Track,
    TransactionState,
    Via,
    ZoneFillEvidence,
    ZoneFillState,
    bind_verified_zone_fill,
    canonical_data,
    stable_hash,
    validate_graph,
)

__all__ = (
    "COMMIT_AUTHORIZATION_SCOPE",
    "COMMIT_AUTHORIZATION_VERSION",
    "ApprovalMismatch",
    "CommitAuthorization",
    "CommitAuthorizationClaims",
    "CommitAuthorizationError",
    "CommitAuthorityClockRollback",
    "CommandConflict",
    "CommandKind",
    "Component",
    "CopperZone",
    "ConsumedCommitAuthorization",
    "DesignCommand",
    "DesignGraph",
    "DesignKernel",
    "DesignRevision",
    "DesignTransaction",
    "FootprintHole",
    "FootprintPad",
    "FootprintPlacement",
    "ExpiredCommitAuthorization",
    "HmacCommitAuthority",
    "HmacCommitVerifier",
    "InvariantViolation",
    "InvalidCommitAuthorization",
    "KernelError",
    "LockedObject",
    "Net",
    "PinDefinition",
    "PinRef",
    "PointNm",
    "ReleaseApprovalEvidence",
    "ReplayedCommitAuthorization",
    "SchematicJunction",
    "SchematicWire",
    "SemanticDiff",
    "StaleRevision",
    "Track",
    "TransactionNotCommittable",
    "TransactionState",
    "Via",
    "ZoneFillEvidence",
    "ZoneFillState",
    "bind_verified_zone_fill",
    "canonical_data",
    "commit_command_hashes_digest",
    "stable_hash",
    "revision_to_verification_board",
    "to_verification_board",
    "validate_graph",
)
