import type { ReferenceControllerProfile } from "../knowledge/reference-controller-v0.js";
import type { StageExecutor } from "../workflow/contracts.js";
import { runKicadBackend } from "./backend-runner.js";
import {
  evidenceDraft,
  finalizeStageResult,
  jsonArtifactDraft,
  prerequisiteBlockers,
  profileFor,
  profileIntegrityBlockers,
  referenceEnvelopeBlockers,
  requirementsApprovalBlockers,
  stageExactInputs
} from "./draft-utils.js";

const manufacturingPlan = (profile: ReferenceControllerProfile) => ({
  schemaVersion: "evleda.manufacturing-plan.v1",
  profileId: profile.profileId,
  boardRevision: profile.boardRevision,
  lifecycle: "candidate",
  packageMarking: "CANDIDATE — NOT FOR MANUFACTURING",
  referenceFabricationParameters: {
    layerCount: profile.stackup.layerCount,
    layers: profile.stackup.layers,
    copperWeightOz: 1,
    surfaceFinish: "ENIG reference choice; fabricator capability and cost require review",
    solderMask: "both sides",
    silkscreen: "both sides; board revision and candidate marking required",
    controlledImpedance: "USB 90 ohm differential geometry must come from the selected fabricator stackup",
    panelization: "not authorized or generated by EvlEDA v0"
  },
  assemblyRequirements: [
    "Complete KiCad BOM with exact orderable MPNs, quantities, references, values, DNP state, and footprints.",
    "Top and bottom position files with a documented coordinate origin, rotation convention, units, and board side.",
    "Paste/mask/copper/silkscreen/outline Gerbers plus plated/non-plated drill outputs.",
    "Assembly drawings and board renders bearing the exact board revision.",
    "CAM manifest binding every output byte to the current schematic and PCB source identities.",
    "No substitutions are authorized by this candidate package."
  ],
  nativeChecks: [
    "Fresh DRC and schematic/PCB parity from the exact current source revision.",
    "BOM parity between KiCad source and exported BOM.",
    "Successful Gerber, drill, and position export reports.",
    "CAM manifest completeness and non-empty-file validation."
  ],
  outputRoles: ["bom", "gerber", "drill", "position", "cam_manifest"],
  releaseBoundary: [
    "This package is review-only and cannot be sent to a fabricator as an autonomous release.",
    "A prototype bundle separately requires a human qualification attestation for the exact manifest.",
    "Manufacturing release requires a separate human release authority and exact physical evidence."
  ],
  nativeSourcePolicy: "Only the configured KiCad backend may generate CAM bytes or native export/check evidence."
});

export const manufacturingPackageStageExecutor: StageExecutor<"manufacturing_package"> = {
  stage: "manufacturing_package",
  async execute(context) {
    const profile = profileFor(context);
    const exactInputs = stageExactInputs(context);
    const initialBlockers = [
      ...prerequisiteBlockers("manufacturing_package", context),
      ...requirementsApprovalBlockers(context),
      ...referenceEnvelopeBlockers(context, profile),
      ...profileIntegrityBlockers(profile, exactInputs)
    ];
    const plan = jsonArtifactDraft({
      logicalName: "manufacturing/manufacturing-plan.json",
      value: manufacturingPlan(profile),
      exactInputs,
      validationStatus: "not_run"
    });
    const initialEvidence = [
      evidenceDraft({
        evidenceClass: "agent_claim",
        claim: "The manufacturing plan enumerates required candidate outputs and release boundaries; it is not CAM or release evidence.",
        subjectDigests: [plan.identity.digest],
        parsedArtifactLogicalName: plan.logicalName,
        exactInputs,
        validationStatus: "not_run"
      })
    ];
    const backend = await runKicadBackend({
      stage: "manufacturing_package",
      context,
      profile,
      exactInputs,
      initialArtifacts: [plan],
      initialEvidence,
      initialBlockers,
      requiredArtifactRoles: ["bom", "gerber", "drill", "position", "cam_manifest"],
      requiredReports: [
        "drc",
        "schematic_parity",
        "bom_parity",
        "bom_export",
        "gerber_export",
        "drill_export",
        "position_export",
        "cam_manifest"
      ]
    });
    return finalizeStageResult(
      "manufacturing_package",
      backend.artifacts,
      backend.evidence,
      backend.blockers
    );
  }
};
