"""Fail-closed project-level KiCad-to-canonical import mapping."""

from .evidence_store import (
    MAPPING_EVIDENCE_STORE_SCHEMA_VERSION,
    CanonicalMappingEvidence,
    IllegalMappingEvidenceTransition,
    InvalidMappingEvidence,
    MappingEvidenceConcurrencyConflict,
    MappingEvidenceDraft,
    MappingEvidenceEvent,
    MappingEvidenceEventKind,
    MappingEvidenceIntegrityError,
    MappingEvidenceNotFound,
    MappingEvidenceRepository,
    MappingEvidenceState,
    MappingEvidenceStoreError,
    MappingEvidenceStoreUnavailable,
    SQLiteMappingEvidenceRepository,
    SQLiteMappingEvidenceStore,
    UnsupportedMappingEvidenceStoreSchema,
)
from .mapper import map_project_import
from .model import (
    CanonicalImportCandidate,
    CanonicalImportTransactionInput,
    ComponentProvenanceBinding,
    ComponentProvenanceRequest,
    ImportMappingInvariantError,
    ImportMappingResult,
    MappingIssue,
    SourcePinPadBinding,
    TrustedComponentProvenanceResolver,
    TrustedComponentResolution,
)

__all__ = (
    "MAPPING_EVIDENCE_STORE_SCHEMA_VERSION",
    "CanonicalImportCandidate",
    "CanonicalImportTransactionInput",
    "CanonicalMappingEvidence",
    "ComponentProvenanceBinding",
    "ComponentProvenanceRequest",
    "IllegalMappingEvidenceTransition",
    "ImportMappingInvariantError",
    "ImportMappingResult",
    "InvalidMappingEvidence",
    "MappingEvidenceConcurrencyConflict",
    "MappingEvidenceDraft",
    "MappingEvidenceEvent",
    "MappingEvidenceEventKind",
    "MappingEvidenceIntegrityError",
    "MappingEvidenceNotFound",
    "MappingEvidenceRepository",
    "MappingEvidenceState",
    "MappingEvidenceStoreError",
    "MappingEvidenceStoreUnavailable",
    "MappingIssue",
    "SQLiteMappingEvidenceRepository",
    "SQLiteMappingEvidenceStore",
    "SourcePinPadBinding",
    "TrustedComponentProvenanceResolver",
    "TrustedComponentResolution",
    "UnsupportedMappingEvidenceStoreSchema",
    "map_project_import",
)
