import { canonicalIdentity, canonicalJson } from "../core/canonical.js";
import type { CanonicalIdentity,ContentIdentity } from "../domain/types.js";
import type { FreshPlaneTraceTopologyAssessment } from "../harness/fresh-plane-trace-topology.js";
import { sanitizePcbDiagnosticText } from "./toolbox-interface-report.js";
const need:(v:unknown,s:string)=>asserts v=(v,s)=>{if(!v)throw new Error(`Trace topology projection: ${s}`);};
const same=(a:unknown,b:unknown)=>canonicalJson(a)===canonicalJson(b);
const keys=(v:object,expected:readonly string[])=>need(same(Object.keys(v).sort(),[...expected].sort()),'unexpected or missing fields');
const text=(s:string)=>{need(typeof s==='string'&&s.length<=4096,'bounded text');return sanitizePcbDiagnosticText(s);};
const integer=(n:number,max=4_000_000)=>{need(Number.isSafeInteger(n)&&n>=0&&n<=max,'bounded integer');return n;};
const boolean=(b:boolean)=>{need(typeof b==='boolean','boolean');return b;};
const canonical=(v:CanonicalIdentity)=>{keys(v,['algorithm','digest','schemaVersion','canonicalizationVersion']);need(v.algorithm==='sha256'&&/^[a-f0-9]{64}$/.test(v.digest)&&v.canonicalizationVersion==='evleda-c14n-json-v1','canonical identity');return{algorithm:v.algorithm,digest:v.digest,schemaVersion:text(v.schemaVersion),canonicalizationVersion:v.canonicalizationVersion};};
const content=(v:ContentIdentity)=>{keys(v,['algorithm','digest','size']);need(v.algorithm==='sha256'&&/^[a-f0-9]{64}$/.test(v.digest),'content identity');return{algorithm:v.algorithm,digest:v.digest,size:integer(v.size,16*1024*1024)};};
type Calculation=NonNullable<FreshPlaneTraceTopologyAssessment['rows'][number]['calculation']>;
const point=(p:NonNullable<Calculation['contacts'][number]['witness']>)=>{keys(p,['x','y']);const fraction=(v:typeof p.x)=>{keys(v,['numerator','denominator']);need(/^-?(?:0|[1-9][0-9]{0,155})$/.test(v.numerator)&&v.numerator!=='-0'&&/^[1-9][0-9]{0,155}$/.test(v.denominator),'exact rational point');return{numerator:v.numerator,denominator:v.denominator};};return{x:fraction(p.x),y:fraction(p.y)};};
function calculation(c:Calculation){
  keys(c,['scope','status','topology','connected','acyclic','leavesTerminateAtPads','simplePath','vertexCount','edgeCount','collapsedSourceEdges','physicalPadCount','trackCount','viaCount','contactCount','coveredContactCount','violations','unresolved','primitiveInteriors','contacts','sourceEdges','nodes','operations','planeCopperUsed','componentInternalTiesInferred','currentCapacityClaimed']);
  need(c.scope==='qualified-source-spine-with-complete-convex-contact-cover'&&['pass','fail','unknown'].includes(c.status)&&['tree','point_to_point'].includes(c.topology)
    &&c.planeCopperUsed===false&&c.componentInternalTiesInferred===false&&c.currentCapacityClaimed===false,'calculation scope');
  const primitives=c.primitiveInteriors.map(p=>{keys(p,['id','kind','connectedCarrier','positiveCopperWitness']);need(['track','pad','via'].includes(p.kind),'primitive kind');return{id:text(p.id),kind:p.kind,connectedCarrier:boolean(p.connectedCarrier),positiveCopperWitness:p.positiveCopperWitness===null?null:point(p.positiveCopperWitness)};});
  need(primitives.length===c.physicalPadCount+c.trackCount+c.viaCount&&new Set(primitives.map(p=>p.id)).size===primitives.length,'complete primitive inventory');
  for(const[kind,count]of[['pad',c.physicalPadCount],['track',c.trackCount],['via',c.viaCount]] as const)need(primitives.filter(p=>p.kind===kind).length===count,'primitive counts');
  const ids=new Set(primitives.map(p=>p.id)),nodes=c.nodes.map(n=>{keys(n,['id','pads','degree','sites']);return{id:integer(n.id,65535),pads:n.pads.map(text),degree:integer(n.degree,65536),sites:n.sites.map(s=>{keys(s,['layer','at']);need(s.layer!==null&&/^(?:F|B|In(?:[1-9]|[12][0-9]|30))\.Cu$/.test(s.layer),'site layer');return{layer:s.layer,at:point(s.at)};})};});
  const nodeIds=new Set(nodes.map(n=>n.id));need(nodes.length===c.vertexCount&&nodeIds.size===nodes.length,'source node inventory');
  const edges=c.sourceEdges.map(e=>{keys(e,['trackUuid','from','to']);need(ids.has(e.trackUuid)&&nodeIds.has(e.from)&&nodeIds.has(e.to)&&e.from!==e.to,'source edge attribution');return{trackUuid:text(e.trackUuid),from:integer(e.from,65535),to:integer(e.to,65535)};});
  need(edges.length===c.edgeCount,'source edge count');
  const contacts=c.contacts.map(p=>{const optional=p.via===undefined?[]:['via'];keys(p,['first','second','kind','witness',...optional]);need(ids.has(p.first)&&ids.has(p.second)&&p.first!==p.second&&['positive-body-contact','exact-source-junction','common-convex-contact-cover'].includes(p.kind),'contact attribution');if(p.via!==undefined)need(ids.has(p.via)&&p.via!==p.first&&p.via!==p.second,'cover primitive');need((p.kind==='common-convex-contact-cover')===(p.via!==undefined)&&p.witness!==null,'contact certificate');return{first:text(p.first),second:text(p.second),kind:p.kind,witness:point(p.witness),...(p.via===undefined?{}:{via:text(p.via)})};});
  need(contacts.length===c.coveredContactCount&&c.coveredContactCount<=c.contactCount,'contact counts');
  if(c.status==='pass')need(c.connected&&c.acyclic&&c.leavesTerminateAtPads&&(c.topology==='tree'||c.simplePath)&&c.violations.length===0&&c.unresolved.length===0
    &&c.edgeCount===c.vertexCount-1&&c.coveredContactCount===c.contactCount&&primitives.every(p=>p.connectedCarrier&&p.positiveCopperWitness!==null),'incomplete topology pass');
  return{scope:c.scope,status:c.status,topology:c.topology,connected:boolean(c.connected),acyclic:boolean(c.acyclic),leavesTerminateAtPads:boolean(c.leavesTerminateAtPads),simplePath:boolean(c.simplePath),
    vertexCount:integer(c.vertexCount,65536),edgeCount:integer(c.edgeCount,65536),collapsedSourceEdges:integer(c.collapsedSourceEdges,65536),physicalPadCount:integer(c.physicalPadCount,512),trackCount:integer(c.trackCount,1536),viaCount:integer(c.viaCount,256),
    contactCount:integer(c.contactCount,131072),coveredContactCount:integer(c.coveredContactCount,131072),violations:c.violations.map(text),unresolved:c.unresolved.map(text),primitiveInteriors:primitives,contacts,sourceEdges:edges,nodes,operations:integer(c.operations),planeCopperUsed:false,componentInternalTiesInferred:false,currentCapacityClaimed:false};
}
export function summarizePlaneTraceTopology(value:FreshPlaneTraceTopologyAssessment,originalRows:readonly{readonly id:string;readonly kind:string;readonly status:string;readonly reasons:readonly string[]}[],nativeClearanceVerified:boolean){
  keys(value,['schemaVersion','bundleIdentity','contractIdentity','libraryBindingIdentity','verificationPlanIdentity','hostScopeIdentity','pcbIdentity','endpointConnectivityIdentity','nativeObservationIdentity','rows','scope','numericalPolicy','planeCopperUsed','electricalSuitabilityEvaluated','fabricationAuthorized','accepted','identity']);
  const {identity,...payload}=value;need(value.schemaVersion==='evleda.fresh-plane-trace-topology.v1'&&same(identity,canonicalIdentity(payload,value.schemaVersion))
    &&value.scope==='source-spine-and-finite-copper-contact-cover-with-complete-native-physical-evidence'&&value.numericalPolicy==='exact-rational-nanometres-with-bounded-positive-witness-search'
    &&value.planeCopperUsed===false&&value.electricalSuitabilityEvaluated===false&&value.fabricationAuthorized===false&&value.accepted===false,'identity or scope');
  const expected=originalRows.filter(r=>r.kind==='trace_connectivity');need(value.rows.length<=128&&new Set(value.rows.map(r=>r.id)).size===value.rows.length&&same(value.rows.map(r=>r.id).sort(),expected.map(r=>r.id).sort()),'original routed-net inventory');
  const rows=value.rows.map(r=>{keys(r,['id','kind','net','topology','status','nativeConnected','reasons','calculation']);const original=expected.find(e=>e.id===r.id)!;need(r.id===`trace-net:${r.net}`&&r.kind==='trace_connectivity'&&['pass','fail','unknown'].includes(r.status),'original net row');
    const effective=r.status==='pass'&&!nativeClearanceVerified?'unknown':r.status;need(original.status===effective,'original row verdict differs');const result=r.calculation===null?null:calculation(r.calculation);
    if(r.status==='pass')need(r.nativeConnected&&result?.status==='pass'&&result.topology===r.topology,'native/source pass mismatch');
    return{id:text(r.id),kind:r.kind,net:text(r.net),topology:r.topology,sourceStatus:r.status,status:original.status,nativeConnected:boolean(r.nativeConnected),reasons:original.reasons.map(text),calculation:result};});
  return{schemaVersion:value.schemaVersion,identity:canonical(identity),bundleIdentity:canonical(value.bundleIdentity),contractIdentity:canonical(value.contractIdentity),libraryBindingIdentity:canonical(value.libraryBindingIdentity),verificationPlanIdentity:canonical(value.verificationPlanIdentity),hostScopeIdentity:canonical(value.hostScopeIdentity),pcbIdentity:content(value.pcbIdentity),endpointConnectivityIdentity:canonical(value.endpointConnectivityIdentity),nativeObservationIdentity:content(value.nativeObservationIdentity),rows,scope:value.scope,numericalPolicy:value.numericalPolicy,planeCopperUsed:false,electricalSuitabilityEvaluated:false,fabricationAuthorized:false,accepted:false};
}
