"""Deterministic transport-neutral human-schematic planning core."""

from .catalog import (
    SourcePayloadProvider,
    SourcePayloadResolver,
    SymbolCatalog,
    default_symbol_catalog,
)
from .emitter import (
    HUMAN_SCHEMATIC_EMITTER_ID,
    HUMAN_SCHEMATIC_EMITTER_VERSION,
    HumanEmissionBinding,
    HumanFootprintLinkFactory,
    HumanSchematicEmission,
    HumanUUIDFactory,
    emit_human_schematic,
    verify_human_schematic_emission,
)
from .layout import R2_PLANNER_ID, R2_PROJECT_ID, default_sheet
from .model import (
    A4_LANDSCAPE_HEIGHT_NM,
    A4_LANDSCAPE_WIDTH_NM,
    GRID_NM,
    ComponentPlacement,
    FunctionalBlock,
    GridEnvelope,
    GridPoint,
    HumanSchematicError,
    HumanSchematicPlan,
    Junction,
    LocalLabel,
    NetMembership,
    NoConnect,
    PinAnchor,
    PinPort,
    PropertyRecord,
    SemanticComponent,
    SemanticGraph,
    SemanticNet,
    SemanticPin,
    SemanticPinDefinition,
    SheetSpec,
    SourceVerification,
    SymbolSource,
    SymbolTemplate,
    WireSegment,
    segment_points,
)
from .planner import plan_r2_human_schematic, semantic_graph_from_design

__all__ = (
    "A4_LANDSCAPE_HEIGHT_NM",
    "A4_LANDSCAPE_WIDTH_NM",
    "GRID_NM",
    "HUMAN_SCHEMATIC_EMITTER_ID",
    "HUMAN_SCHEMATIC_EMITTER_VERSION",
    "R2_PLANNER_ID",
    "R2_PROJECT_ID",
    "ComponentPlacement",
    "FunctionalBlock",
    "GridEnvelope",
    "GridPoint",
    "HumanSchematicError",
    "HumanEmissionBinding",
    "HumanFootprintLinkFactory",
    "HumanSchematicEmission",
    "HumanSchematicPlan",
    "HumanUUIDFactory",
    "Junction",
    "LocalLabel",
    "NetMembership",
    "NoConnect",
    "PinAnchor",
    "PinPort",
    "PropertyRecord",
    "SemanticComponent",
    "SemanticGraph",
    "SemanticNet",
    "SemanticPin",
    "SemanticPinDefinition",
    "SheetSpec",
    "SourcePayloadProvider",
    "SourcePayloadResolver",
    "SourceVerification",
    "SymbolCatalog",
    "SymbolSource",
    "SymbolTemplate",
    "WireSegment",
    "default_sheet",
    "default_symbol_catalog",
    "emit_human_schematic",
    "plan_r2_human_schematic",
    "segment_points",
    "semantic_graph_from_design",
    "verify_human_schematic_emission",
)
