"""Deterministic placement/routing candidate validation."""

from .canonical import CanonicalizationError, canonical_data, canonical_json_bytes, stable_hash
from .hashing import (
    attestation_hash,
    candidate_artifact_hash,
    contract_hash,
    manifest_hash,
    replay_hash,
    seal_manifest,
    seal_replay,
)
from .model import (
    CandidateManifest,
    DifferentialPairLimit,
    DifferentialPairSkew,
    DrcBlocker,
    HardConstraintResult,
    LockedObjectState,
    NetRouteLimit,
    NetRouteMetrics,
    ObjectiveDirection,
    ObjectiveValue,
    ReplayRecord,
    ResourceBudget,
    ResourceUsage,
    SolverIdentity,
    TrustedValidationAttestation,
    ValidationContract,
    ValidationFinding,
    ValidationResult,
    ValidationState,
)
from .validator import AttestationVerifier, LayoutCandidateValidator

__all__ = [
    "AttestationVerifier",
    "CandidateManifest",
    "CanonicalizationError",
    "DifferentialPairLimit",
    "DifferentialPairSkew",
    "DrcBlocker",
    "HardConstraintResult",
    "LayoutCandidateValidator",
    "LockedObjectState",
    "NetRouteLimit",
    "NetRouteMetrics",
    "ObjectiveDirection",
    "ObjectiveValue",
    "ReplayRecord",
    "ResourceBudget",
    "ResourceUsage",
    "SolverIdentity",
    "TrustedValidationAttestation",
    "ValidationContract",
    "ValidationFinding",
    "ValidationResult",
    "ValidationState",
    "attestation_hash",
    "candidate_artifact_hash",
    "canonical_data",
    "canonical_json_bytes",
    "contract_hash",
    "manifest_hash",
    "replay_hash",
    "seal_manifest",
    "seal_replay",
    "stable_hash",
]
